import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AudioProvider } from "@/hooks/useAudioContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans", // Chúng ta sẽ dùng biến CSS này
});

export const metadata: Metadata = {
  title: "Ai thông minh hơn nhân viên Midu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-radial from-white from-40% to-pink-300`}>
        <AudioProvider>{children}</AudioProvider>
      </body>
    </html>
  );
}
