import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AudioProvider } from "@/hooks/useAudioContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans", // Chúng ta sẽ dùng biến CSS này
});

export const metadata: Metadata = {
  title: "Siêu trí tuệ Midu",
  description: "Generated by create next app",
  icons: {
    icon: 'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🧠</text></svg>',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-radial from-white from-40% to-pink-300`}>
        <AudioProvider>{children}</AudioProvider>
      </body>
    </html>
  );
}
